const data = {
    products:[
     {
    _id:'1',
    name:'adidas',
    category:'Shirt',
    Image:'/images/p1.jpg',
    price:'120',
    brand:'Adidas',
    rating:'4.5',
    numReview: 10,
    description: 'high quality product',
     },   
     {
        _id:'2',
        name:'Nike slim Pant',
        category:'pant',
        Image:'/images/p4.jpg',
        price:'100',
        brand:'Adidas',
        rating:'4.0',
        numReview: 10,
        description: 'high quality product',
         }, 
         {
            _id:'3',
            name:'Nike slim shirt',
            category:'Shirt',
            Image:'/images/p3.jpg',
            price:'80',
            brand:'Adidas',
            rating:'4.8',
            numReview: 17,
            description: 'high quality product',
             }, 
             {
                _id:'4',
                name:'Slim pant',
                category:'pant',
                Image:'/images/p4.jpg',
                price:'70',
                brand:'Adidas',
                rating:'4.5',
                numReview: 14,
                description: 'high quality product',
                 }, 
                 {
                    _id:'5',
                    name:'Formal Pant',
                    category:'pant',
                    Image:'/images/p6.jpg',
                    price:'130',
                    brand:'Adidas',
                    rating:'4.0',
                    numReview: 10,
                    description: 'high quality product',
                     }, 
                     {
                        _id:'6',
                        name:'Nike slim shirt',
                        category:'Shirt',
                        Image:'/images/p1.jpg',
                        price:'150',
                        brand:'Adidas',
                        rating:'4.5',
                        numReview: 15,
                        description: 'high quality product',
                         }, 

    ],
};
export default data;